### ISSUE TITLE
ofPattern throws vague IllegalArgumentException

### ISSUE THREAD

**Issue by alex2** [js-joda/js-joda#193]
Hi, only been using js-joda for a couple of hours so the issue very likely is at my end but I'd really appreciate some help.

All my attempts at using ofPattern to parse an RFC2822 string seem to throw an empty `IllegalArgumentException`. The docs imply I should be using a string argument so I assume I'm using some of the patterns incorrectly.

The pattern I'm using is `'EEE MMM dd HH:mm:ss Z yyyy'`, more specifics below.

Many thanks.

```
$ grep js-joda package.json
    "js-joda": "^1.5.2",
    "js-joda-timezone": "^1.1.5",
```

```
> require('js-joda').use(require('js-joda-timezone')).DateTimeFormatter.ofPattern('EEE MMM dd HH:mm:ss Z yyyy')
IllegalArgumentException
    at DateTimeFormatterBuilder.appendText (node_modules/js-joda/dist/js-joda.js:4828:15)
    at DateTimeFormatterBuilder._parseField (node_modules/js-joda/dist/js-joda.js:5098:30)
    at DateTimeFormatterBuilder._parsePattern (node_modules/js-joda/dist/js-joda.js:4893:26)
    at DateTimeFormatterBuilder.appendPattern (node_modules/js-joda/dist/js-joda.js:4819:14)
    at Function.ofPattern (node_modules/js-joda/dist/js-joda.js:2194:73)
    at repl:1:71
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
```

```
> require('js-joda').DateTimeFormatter.ofPattern('EEE MMM dd HH:mm:ss Z yyyy')
IllegalArgumentException
    at DateTimeFormatterBuilder.appendText (node_modules/js-joda/dist/js-joda.js:4828:15)
    at DateTimeFormatterBuilder._parseField (node_modules/js-joda/dist/js-joda.js:5098:30)
    at DateTimeFormatterBuilder._parsePattern (node_modules/js-joda/dist/js-joda.js:4893:26)
    at DateTimeFormatterBuilder.appendPattern (node_modules/js-joda/dist/js-joda.js:4819:14)
    at Function.ofPattern (node_modules/js-joda/dist/js-joda.js:2194:73)
    at repl:1:38
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
```

**Comment by phueper** [comment]
Hi @alex2

Thanks for reporting this and thanks for using js-joda

The problem here is, that you are using `EEE` and `MMM` patterns... Both would produce a localized text for day-of-week and month-of-year. Localized strings are not supported in js-joda for size reasons. You need to use the (just released)  js-joda-locale package. Or you can use the two letter versions of the patterns which would produce numbers.

Regards, Pattrick

**Comment by phueper** [comment]
One Note... If you do decide to try js-joda-locale, i would be very happy to provide support.  We really just released this yesterday in a first 0.1.0 version. I'm very much interested in user feedback of the package to learn about the experience using it.

Regards, Pattrick

**Comment by phueper** [comment]
fwiw... i installed locally:

- js-joda
- js-joda-timezone
- js-joda-locale
and the peer dependencies of js-joda-locale
- cldr-data
- cldrjs

and then ran: 

```
var _jsJoda = require('js-joda');
var _jsJodaTimezone = require('js-joda-timezone');
var _jsJodaLocale = require('js-joda-locale');

_jsJoda.use(_jsJodaTimezone).use(_jsJodaLocale)

var dateFormatter = _jsJoda.DateTimeFormatter.ofPattern('EEE MMM dd HH:mm:ss Z yyyy').withLocale(_jsJoda.Locale.GERMANY);

var date = _jsJoda.LocalDate.now();

console.log(dateFormatter.format(date));
```

which resulted in `Do. Okt. 19 10 2017`

**Comment by phueper** [comment]
i updated the above comment, it didn't work before, i copied an older version of the code... sry... for Z and the Time pattern to work, you need to use a `ZonedDateTime`

**Comment by phueper** [comment]
parsing the pattern back also seems to work: 

```
var _jsJoda = require('js-joda');
var _jsJodaTimezone = require('js-joda-timezone');
var _jsJodaLocale = require('js-joda-locale');

_jsJoda.use(_jsJodaTimezone).use(_jsJodaLocale)

var dateFormatter = _jsJoda.DateTimeFormatter.ofPattern('EEE MMM dd HH:mm:ss Z yyyy').withLocale(_jsJoda.Locale.US);

var date = _jsJoda.ZonedDateTime.now();

const dateString = dateFormatter.format(date)

console.log(dateString);

const parsedDate = _jsJoda.ZonedDateTime.from(dateFormatter.parse(dateString));

console.log(parsedDate);
```
results in:
```
Sat Oct 21 20:07:52 +0200 2017
ZonedDateTime {
  _dateTime: 
   LocalDateTime {
     _date: LocalDate { _year: 2017, _month: 10, _day: 21 },
     _time: LocalTime { _hour: 20, _minute: 7, _second: 52, _nano: 0 } },
  _offset: 
   ZoneOffset {
     _totalSeconds: 7200,
     _rules: Fixed { _offset: [Circular] },
     _id: '+02:00' },
  _zone: 
   ZoneOffset {
     _totalSeconds: 7200,
     _rules: Fixed { _offset: [Circular] },
     _id: '+02:00' } }
```
which looks ok to me... i will close this issue, feel free to reopen if you have further questions
