### ISSUE TITLE
Locales w/ TypeScript?

### ISSUE THREAD

**Issue by efenderbosch** [js-joda/js-joda#483]
My `package.json` has
```json
    "@js-joda/core": "^3.2.0",
    "@js-joda/locale_en": "^3.2.2",
    "@js-joda/timezone": "^2.5.0",
```

When importing `Locale` via `import { Locale } from '@js-joda/locale_en'` I get `could not find declaration for module '@js-joda/locale_en'`.

I tried adding a `shims-js-joda.d.ts` file w/ `declare module '@js-joda/locale_en'` but then get:

```
Error: Cannot find module './main/en-US/ca-gregorian.json'
    at webpackContextResolve (node_modules/@js-joda/locale_en/dist/index.js:337:11)
    at webpackContext (node_modules/@js-joda/locale_en/dist/index.js:332:11)
    at ./utils/load_cldrData.prebuilt.js.module.exports (node_modules/@js-joda/locale_en/dist/index.js:6560:85)
    at loadCldrData (node_modules/@js-joda/locale_en/dist/index.js:4636:104)
    at CldrDateTimeTextProvider._createStore (node_modules/@js-joda/locale_en/dist/index.js:4906:70)
    at CldrDateTimeTextProvider._findStore (node_modules/@js-joda/locale_en/dist/index.js:4897:22)
    at CldrDateTimeTextProvider.getText (node_modules/@js-joda/locale_en/dist/index.js:4871:24)
    at TextPrinterParser.print (node_modules/@js-joda/locale_en/dist/index.js:5590:33)
    at CompositePrinterParser.print (node_modules/@js-joda/core/src/format/parser/CompositePrinterParser.js:38:24)
    at DateTimeFormatter._formatTo (node_modules/@js-joda/core/src/format/DateTimeFormatter.js:422:29)
    at DateTimeFormatter.format (node_modules/@js-joda/core/src/format/DateTimeFormatter.js:398:14)
    at ZonedDateTime.format (node_modules/@js-joda/core/src/chrono/ChronoZonedDateTime.js:43:26)
    ...
```

when I try to use a `DateTimeFormatter` with a localization format pattern. I don't see anything I've missed in https://js-joda.github.io/js-joda/manual/formatting.html

Is there something else I'm missing?

**Comment by efenderbosch** [comment]
I found https://github.com/js-joda/js-joda-locale/issues/122 and that solved the problem.

```TypeScript
declare module '@js-joda/locale_en' {
    import { Locale } from '@js-joda/core'
    export const Locale: {
        US: Locale
    }
}
```
