### ISSUE TITLE
Interval.parse hangs/fails

### ISSUE THREAD

**Issue by xenoterracide** [js-joda/js-joda#653]
```ts
Interval.parse('2022-12-07T18:55:57.651Z/+1000000-12-31T23:59:59.999999999Z')
```

hangs. This was created by

```ts
`${Interval.of(Instant.now(), Instant.MAX)}`
```

takes a very long time to get to this stack trace
```
    DateTimeParseException: Text '+1000000-12-31T23:59:59.999999999Z' could not be parsed: Invalid int value for Year: 1000000: +1000000-12-31T23:59:59.999999999Z, at index: 0
    -------
    Caused by: DateTimeException: Invalid int value for Year: 1000000

      12 |   params: TransformFnParams,
      13 | ): Interval {
    > 14 |   return Interval.parse(params.value);
         |                   ^
      15 | }
      16 |
      17 | export function transformIntervalToString(params: TransformFnParams): string {

      at ValueRange.checkValidIntValue (../../node_modules/@js-joda/core/src/temporal/ValueRange.js:135:19)
      at ChronoField.checkValidIntValue (../../node_modules/@js-joda/core/src/temporal/ChronoField.js:307:29)
      at IsoChronology.resolveDate (../../node_modules/@js-joda/core/src/chrono/IsoChronology.js:115:48)
      at DateTimeBuilder._mergeDate (../../node_modules/@js-joda/core/src/format/DateTimeBuilder.js:174:48)
      at DateTimeBuilder.resolve (../../node_modules/@js-joda/core/src/format/DateTimeBuilder.js:149:14)
      at DateTimeFormatter.parse2 (../../node_modules/@js-joda/core/src/format/DateTimeFormatter.js:491:62)
      at DateTimeFormatter.parse (../../node_modules/@js-joda/core/src/format/DateTimeFormatter.js:439:25)
      at Function.parse (../../node_modules/@js-joda/core/src/ZonedDateTime.js:485:26)
      at Function.parse (../../node_modules/@js-joda/extra/src/Interval.js:137:47)
      at Object.transformIntervalToInstance [as transformFn] (../../libs/core/src/utilities/time.ts:14:19)
      -------
      at DateTimeFormatter._createError (../../node_modules/@js-joda/core/src/format/DateTimeFormatter.js:509:16)
      at DateTimeFormatter.parse2 (../../node_modules/@js-joda/core/src/format/DateTimeFormatter.js:497:28)
      at DateTimeFormatter.parse (../../node_modules/@js-joda/core/src/format/DateTimeFormatter.js:439:25)
      at Function.parse (../../node_modules/@js-joda/core/src/ZonedDateTime.js:485:26)
      at Function.parse (../../node_modules/@js-joda/extra/src/Interval.js:137:47)
      at Object.transformIntervalToInstance [as transformFn] (../../libs/core/src/utilities/time.ts:14:19)
      at ../../node_modules/src/TransformOperationExecutor.ts:412:24
          at Array.forEach (<anonymous>)
      at TransformOperationExecutor.applyCustomTransformations (../../node_modules/src/TransformOperationExecutor.ts:411:15)
      at TransformOperationExecutor.transform (../../node_modules/src/TransformOperationExecutor.ts:334:33)
  ```

**Comment by perceptron8** [comment]
`Interval.parse` is indeed buggy, but shouldn't hang - at least it doesn't when I run it.

I'm in the process of rewriting `Interval.parse` on [threeten-extra](https://github.com/ThreeTen/threeten-extra) side, next I would like to fix this one too. Is that ok with you, @pithu?

@xenoterracide Thanks for reporting!

**Comment by pithu** [comment]
Thanks for reporting! 

Next week i will find some time to look at all your issues. 

And yes, we are open for PR's fixing stuff, of course. The extra package was community driven anyway.

**Comment by perceptron8** [comment]
I'm waiting for ThreeTen/threeten-extra/pull/242 to be merged, wish me luck ;)

**Comment by xenoterracide** [comment]
Any activity?

**Comment by perceptron8** [comment]
Unfortunately, no. I'm still waiting.
