### ISSUE TITLE
Parsing Examples Broken

### ISSUE THREAD

**Issue by Crisfole** [js-joda/js-joda#688]
I've followed the directions for parsing with locale closely, but the following code fails when trying to create the pattern (since Locale is being set _after_ `ofPattern` is called:

```ts
import '@js-joda/timezone';
import { Locale as EnglishTimeLocale } from '@js-joda/locale_en-us';
import { LocalDateTime, DateTimeFormatter } from "js-joda";

const formatter = DateTimeFormatter
    .ofPattern("M/d/yyyy H:m:s z")
    .withLocale(EnglishTimeLocale);

console.log(DateTimeStringSchema.parse("09/03/2019 22:14:26 MDT"));
```

Execute with `npx ts-node ./the-file.ts`

I don't get to the console.log. The message is the classic "Pattern using (localized) text not implemented, use js-joda-locale plugin!"

Versions installed are:

```
"@js-joda/locale_en-us": "^4.8.10",
"@js-joda/timezone": "^2.18.0",
"js-joda": "^1.11.0",
```

Stack Trace (slightly redacted):

```
/home/chris/dirname/node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:816
        throw new IllegalArgumentException('Pattern using (localized) text not implemented, use js-joda-locale plugin!');
              ^
IllegalArgumentException: Pattern using (localized) text not implemented, use js-joda-locale plugin!
    at DateTimeFormatterBuilder.appendZoneText (/home/chris/dirname/node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:816:15)
    at DateTimeFormatterBuilder._parsePattern (/home/chris/dirname/node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:896:30)
    at DateTimeFormatterBuilder.appendPattern (/home/chris/dirname/node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:807:14)
    at Function.ofPattern (/home/chris/dirname/node_modules/js-joda/src/format/DateTimeFormatter.js:257:47)
    at file:///home/chris/dirname/src/api/payloads/DateTimeString.ts:9:6
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15) {
  toString: [Function (anonymous)]
}
```

**Comment by Crisfole** [comment]
I'm beginning to *strongly* suspect that the order of imports is _super_ important in how the plugins work...

A Copy and paste from the [formatting page](
https://js-joda.github.io/js-joda/manual/formatting.html) fails. Only change is the Locale import path to match en-us which I had installed:

```ts
import '@js-joda/timezone' // Just needs to be imported; registers itself automatically
import { Locale } from '@js-joda/locale_en-us' // Get `Locale` from the prebuilt package of your choice
import { DateTimeFormatter, LocalDateTime } from 'js-joda'

const d = LocalDateTime.parse('2018-04-28T12:34')
const formatter = DateTimeFormatter
  .ofPattern('eeee (d MMMM)')
  .withLocale(Locale.FRANCE)
d.format(formatter) // samedi (28 avril)
```

Copy and paste from ["using locale" page](https://js-joda.github.io/js-joda/manual/Locale.html) works fine:

```ts
import {
    DateTimeFormatter,
    ZonedDateTime,
    ZoneId,
} from '@js-joda/core';
import '@js-joda/timezone';

import {
    Locale,
} from '@js-joda/locale_en-us';

var zdt = ZonedDateTime.of(2016, 1, 1, 0, 0, 0, 0, ZoneId.of('Europe/Berlin'));
console.log('en_US formatted string:',
    zdt.format(
        DateTimeFormatter
            .ofPattern('eeee MMMM dd yyyy GGGG, hh:mm:ss a zzzz, \'Week \' ww, \'Quarter \' QQQ')
            .withLocale(Locale.US)));

```

So I think there are two work items for this ticket:

 1. Correct the actively misleading documentation on the formatting/parsing page.
 2. Figure out why the import order matters.

**Comment by Crisfole** [comment]
I worked it out! The instructions on the locale page import from `@js-jode/core` where the formatting page imports from `js-joda`. I think some more clarity on that is in order.
